config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"
  devise_for :users
  devise_scope :user do
    get "signup", :to => "devise/registrations#new", as: :signup
    get "signin", :to => "devise/sessions#new", as: :signin
    get "logout", :to => "devise/sessions#destroy", as: :logout
  end
  
  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: "statuses#index"  

  get '/:id', to: 'profiles#show'

  

end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  
  validates :content, presence: true,
                      length: { minimum: 2 }
                      
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  validates :first_name, presence: true   
  validates :last_name, presence: true   
  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                             with: /\A[a-zA-Z0-9_-]+\z/, 
                             message: 'must be formatted correctly.'
                           }
         
  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships 
  
  def full_name
    first_name + " " + last_name
  end
  
  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)
    
    "http://gravatar.com/avatar/#{hash}"
  end
  
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_filter :configure_devise_params, if: :devise_controller?
    def configure_devise_params
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation)
      end
      #devise_parameter_sanitizer.for(:account_update) do |u|
       # u.permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation)
      # end
    end
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.to_a
      render action: :show
    else
    render file: 'public/404', status: 404, format: [:html]
    end
  end  
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
   
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id) 
    end 
    
    respond_to do |format|
      if @status.update_attributes(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content, :user_id) if params[:status]      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(type)
    case type
    when :alert
      "alert-danger"
    when :notice
      "alert-info"
    else
      ""
    end   
  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <%= link_to "Treebook", feed_path, class: 'navbar-brand' %>
	
	  </div>
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav navbar-right">
				
				<% if user_signed_in? %>
					<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
					<li><%= link_to "Log out", logout_path %></li>
				<% else %>
					<li><%= link_to "Sign up", signup_path %></li>
					<li><%= link_to "Sign in", signin_path %></li>
				<% end %>

	    </ul>
	  </div><!-- /.navbar-collapse -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	
	<div class="container">
		
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
				<%= message %>
			</div>
		
		<% end %>
		
		<div class="row">
			<%= yield %>
		</div>
		
	</div>

</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="panel panel-default">
			<div class="panel-body">
				<%= status.content %>
				<hr/>
				<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
			</div>
		</div>
	<% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<%= f.input :content %>
	
  <div class="actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>All Statuses</h1>

<%= link_to 'Post a new status', new_status_path, class: "btn btn-primary" %>
<% @statuses.each do |status| %>
<div class="status panel panel-default">
	<div class="panel-body">
	<p>
		<%= image_tag status.user.gravatar_url %>
	</p>
	<p>
		<b>Name: <%= status.user.full_name %></b>
	<p>
		<%= status.content %>
	</p>
	<hr/>
	<div class="meta">
		<%= link_to time_ago_in_words(status.created_at) + " ago", status %>
		<span class="admin">
			| <%= link_to 'Edit', edit_status_path(status) %>
			| <%= link_to 'Delete', status, method: :delete, data: { confirm: 'Are you sure you want to delete this status?' } %>
		</span>
	</div>
	</div>
</div>
<% end %>
 

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<b>Name: <%= @status.user.full_name %></b>
</p>
<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>